naam = input("wat is je naam:")
adres = input("wat is je adres?:")
postcode = input("wat is je adres?:")
woonplaats = input("wat is je woonplaats?:")

print ("----------------------------------------------------")
print (f" naam:{naam}")
print (f" adres:{adres}")
print (f" postcode:{postcode}")
print (f" woonplaats:{woonplaats}")
print ("----------------------------------------------------")